//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidMvcServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Dept
    {
        public Tb_Dept()
        {
            this.Tb_User = new HashSet<Tb_User>();
        }
    
        public string DepId { get; set; }
        public string DepName { get; set; }
        public string ParentDepId { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
    
        public virtual ICollection<Tb_User> Tb_User { get; set; }
    }
}
