//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidMvcServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_User
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> Status { get; set; }
        public string DeptId { get; set; }
        public bool Gender { get; set; }
        public byte[] Photo { get; set; }
        public string Signature { get; set; }
        public string CellPhone { get; set; }
        public string OfficePhone { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
    
        public virtual Tb_Dept Tb_Dept { get; set; }
    }
}
